name: 2º  - Recolector y análisis del día

on:
  schedule:
    - cron: '0 7 * * *' # 08:00 AM España
  workflow_dispatch:
    inputs:
      mode:
        description: 'Execution Mode'
        required: true
        default: 'all'
        type: choice
        options: [fetch, analyze, all]

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r backend/requirements.txt
        
    - name: Run AI Prediction Engine
      env:
        # AQUÍ mapeamos los Secrets de GitHub a las variables que lee Python
        API_KEY: ${{ secrets.API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        REDIS_URL: ${{ secrets.REDIS_URL }}
        REDIS_TOKEN: ${{ secrets.REDIS_TOKEN }}
      run: |
        cd backend
        python main.py --mode ${{ inputs.mode || 'all' }}
        
    # SE HA ELIMINADO EL PASO DE COMMIT Y PUSH
    # Las apuestas van directo a Redis.