name: 2º - Recolector de datos API
on:
  schedule:
    - cron: '0 7 * * *' # 08:00 AM España
  workflow_dispatch:
    inputs:
      mode:
        description: 'Execution Mode'
        required: true
        default: 'fetch'
        type: choice
        options: [fetch]

jobs:
  run-fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r backend/requirements.txt
        
    - name: Run Data Fetcher
      env:
        API_KEY: ${{ secrets.API_KEY }}
        REDIS_URL: ${{ secrets.REDIS_URL }}
        REDIS_TOKEN: ${{ secrets.REDIS_TOKEN }}
      run: |
        cd backend
        python main.py --mode fetch